name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check Workers
        run: npx tsc --noEmit
      
      - name: Install frontend dependencies
        working-directory: ./pages-frontend
        run: npm ci
      
      - name: Type check Frontend
        working-directory: ./pages-frontend
        run: npx tsc --noEmit

  deploy-workers:
    name: Deploy Workers
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy

  deploy-pages:
    name: Deploy Pages Frontend
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      deployments: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install frontend dependencies
        working-directory: ./pages-frontend
        run: npm ci
      
      - name: Build frontend
        working-directory: ./pages-frontend
        run: npm run build
        env:
          VITE_API_URL: https://cf-ai-repo-socratic-mentor.suranganath.workers.dev/api
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy pages-frontend/dist --project-name=socratic-mentor --branch=main
